name: "Suggest a feature"
description: "Suggest a missing feature to be added to Jeff."
title: "[Feature]: "
labels: ["feature", "triage"]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature description
      description: Please provide a description of the feature to propose to be added.
    validations:
      required: true